{% set version = "3.0.0" %}

package:
  name: mpi
  version: {{ version }}

source:
  url: https://github.com/TRIQS/mpi/releases/download/{{ version }}/mpi-{{ version }}.tar.gz
  sha256: PUT HERE THE SHA256 OF YOUR RELEASE TARBALL

build:
  number: 0
  skip: True  # [win or py<30]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ mpi }}
    - libblas
    - liblapack
  run:
    - {{ mpi }}
    - libblas
    - liblapack

about:
  home: https://triqs.github.io/mpi
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'mpi is a high-level C++ interface to the Message Passing Interface'

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
